### ISSUE TITLE
the ips_lists error

### ISSUE THREAD

**Issue by brahmanggi** [z-alami/IpGeo#1]
Hello, I've got an error like this when I try to analyze the pcap :

```
Traceback (most recent call last):
  File "/home/neo/IpGeo/ipGeo.py", line 73, in <module>
    ips = read_pcap(pcap_path)
  File "/home/neo/IpGeo/ipGeo.py", line 18, in read_pcap
    ips_list(ips)
  File "/home/neo/IpGeo/ipGeo.py", line 37, in ips_list
    get_ip_info(ips_lists)
  File "/home/neo/IpGeo/ipGeo.py", line 55, in get_ip_info
    export_result(dic_data)
  File "/home/neo/IpGeo/ipGeo.py", line 63, in export_result
    for i in data[0].keys():
IndexError: list index out of range

```

**Comment by z4l4mi** [comment]
Hey, thanks for reporting this bug, can you send me please the Pcap file
